spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: move
  # swagger - spring docs
  spring-doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    # hikari
    hikari:
      idleTimeout: 180000
      connectionTimeout: 30000
      leakDetectionThreshold: 15000
      connectionTestQuery: SELECT 1
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# kakao
kakao:
  auth:
    base-host: https://kauth.kakao.com
    api-key : ${KAKAO_REST_API_KEY}
logging:
  level:
    reactor.netty.http.client: DEBUG