  name: DEPLOY_DEV_ON_GCP_APP_ENGINE

  on:
    pull_request:
      branches: [develop]
      types: [closed]
    workflow_dispatch:

  permissions: write-all

  jobs:
    deploy:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
        - name: 저장소 체크아웃
          uses: actions/checkout@v4

        - name: Java 17 설정
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Google Cloud 인증
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Google Cloud SDK 설정
          run: |
            curl -sSL https://sdk.cloud.google.com | bash
            echo "source ~/google-cloud-sdk/path.bash.inc" >> ~/.bashrc
            source ~/.bashrc
            gcloud version

        - name: GCP 프로젝트 설정
          run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

        - name: Gradle 실행 권한 부여
          run: chmod +x ./gradlew

        - name: Spring Boot 애플리케이션 빌드
          run: ./gradlew bootJar

        - name: Update app.yaml with github secrets
          run: |
            echo "Updating app.yaml with environment variables using github secrets ..."
            sed -i 's|SUPABASE_DB_USERNAME|'${{ secrets.SUPABASE_DB_USERNAME }}'|g' app.yaml
            sed -i 's|SUPABASE_DB_PASSWORD|'${{ secrets.SUPABASE_DB_PASSWORD }}'|g' app.yaml

        - name: App Engine에 배포
          run: gcloud app deploy --stop-previous-version --quiet --set-env-vars SUPABASE_DB_USERNAME=${{ secrets.SUPABASE_DB_USERNAME }},SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}